version: '3.5'

services:
  dotnet-agent-portal-gateway:
    build: 
      context: ../
      dockerfile: AgentPortalApiGateway/Dockerfile
    image: dotnet-agent-portal-gateway
    container_name: dotnet-agent-portal-gateway
    networks:
      - poc_default
    #    network_mode: host
    ports:
      - "8099:80"
    environment:
      eureka__client__serviceUrl: "http://eureka-server:8761/eureka"
      eureka__client__shouldRegisterWithEureka: "false"
      eureka__client__ValidateCertificates: "false"

  dotnet-auth-service:
    build: 
      context: ../
      dockerfile: AuthService/Dockerfile
    image: dotnet-auth-service
    container_name: dotnet-auth-service
    networks:
      - poc_default
    #    network_mode: host
    ports:
      - "6060:80"
    environment:
      eureka__client__serviceUrl: "http://eureka-server:8761/eureka"
  
  dotnet-chat-service:
    build: 
      context: ../
      dockerfile: ChatService/Dockerfile
    image: dotnet-chat-service
    container_name: dotnet-chat-service
    networks:
      - poc_default
    #    network_mode: host
    ports:
      - "4099:80"
    environment:
      eureka__client__serviceUrl: "http://eureka-server:8761/eureka"
      ConnectionStrings__RabbitMQ: "rabbit"

  dotnet-payment-service:
    build: 
      context: ../
      dockerfile: PaymentService/Dockerfile
    image: dotnet-payment-service
    container_name: dotnet-payment-service
    networks:
      - poc_default
      #    network_mode: host
    ports:
      - "5070:80"
    environment:
      eureka__client__serviceUrl: "http://eureka-server:8761/eureka"
      ConnectionStrings__RabbitMQ: "rabbit"
      ConnectionStrings__DefaultConnection: "THIS IS A SECRET"
      ConnectionStrings__PgConnection: "User ID=lab_user;Password=lab_pass;Database=lab_netmicro_policy;Host=postgres;Port=5432"
      BackgroundJobs__HangfireConnectionStringName: "User ID=lab_user;Password=lab_pass;Database=lab_netmicro_jobs;Host=postgres;Port=5432"
      BackgroundJobs__InPaymentFileFolder: "/mnt/bigdisk/dotnetpoc/testcases"

  dotnet-policy-search-service:
    build: 
      context: ../
      dockerfile: PolicySearchService/Dockerfile
    image: dotnet-policy-search-service
    container_name: dotnet-policy-search-service
    networks:
      - poc_default
    #    network_mode: host
    ports:
      - "5060:80"
    environment:
      eureka__client__serviceUrl: "http://eureka-server:8761/eureka"
      eureka__client__shouldRegisterWithEureka: "true"
      eureka__client__ValidateCertificates: "false"
      eureka__instance__appName: "PolicySearchService"
      eureka__instance__port: "80"
      eureka__instance__hostName: "dotnet-policy-search-service"
      ConnectionStrings__ElasticSearchConnection: "http://elasticsearch:9200"
      ConnectionStrings__RabbitMQ: "rabbit"

  dotnet-policy-service:
    build: 
      context: ../
      dockerfile: PolicyService/Dockerfile
    image: dotnet-policy-service
    container_name: dotnet-policy-service
    networks:
      - poc_default
  #    network_mode: host
    ports:
      - "5050:80"
    environment:
      eureka__client__serviceUrl: "http://eureka-server:8761/eureka"
      eureka__client__shouldRegisterWithEureka: "true"
      eureka__client__ValidateCertificates: "false"
      eureka__instance__appName: "PolicyService"
      eureka__instance__port: "80"
      eureka__instance__hostName: "dotnet-policy-service"
      ConnectionStrings__DefaultConnection: "User ID=lab_user;Password=lab_pass;Database=lab_netmicro_policy;Host=postgres;Port=5432"
      ConnectionStrings__RabbitMQ: "rabbit"
      PricingServiceUri: "http://PricingService/api/pricing"


  dotnet-pricing-service:
    build: 
      context: ../
      dockerfile: PricingService/Dockerfile
    image: dotnet-pricing-service
    container_name: dotnet-pricing-service
    networks:
      - poc_default
    #    network_mode: host
    ports:
      - "5040:80"
    environment:
      eureka__client__serviceUrl: "http://eureka-server:8761/eureka"
      eureka__client__shouldRegisterWithEureka: "true"
      eureka__client__ValidateCertificates: "false"
      eureka__instance__appName: "PricingService"
      eureka__instance__port: "80"
      eureka__instance__hostName: "dotnet-pricing-service"
      ConnectionStrings__DefaultConnection: "User ID=lab_user;Password=lab_pass;Database=lab_netmicro_policy;Host=postgres;Port=5432"

  dotnet-product-service:
    build: 
      context: ../
      dockerfile: ProductService/Dockerfile
    image: dotnet-product-service
    container_name: dotnet-product-service
    networks:
      - poc_default
#    network_mode: host
    ports:
      - "5030:80"
    environment:
      eureka__client__serviceUrl: "http://eureka-server:8761/eureka"
      eureka__client__shouldRegisterWithEureka: "true"
      eureka__client__ValidateCertificates: "false"
      eureka__instance__appName: "ProductService"
      eureka__instance__port: "80"
      eureka__instance__hostName: "dotnet-product-service"

  dotnet-web-vue:
    build: ../Web
    image: dotnet-web-vue
    container_name: dotnet-web-vue
    networks:
      - poc_default
    #    network_mode: host
    ports:
      - "5222:80"
    environment:
      eureka__client__serviceUrl: "http://eureka-server:8761/eureka"
      VUE_APP_BACKEND_URL: "http://dotnet-agent-portal-gateway:8099/api/"
      VUE_APP_AUTH_URL: "http://dotnet-auth-service:6060/api/"
      VUE_APP_BOT_URL: "https://webchat.botframework.com/embed/YOUR_BOT_NAME?s=YOUR_SECRET_KEY"
      VUE_APP_CHAT_URL: "http://dotnet-chat-service:4099"
      
networks:
  poc_default:
    name: poc_default