version: '3.5'

services:
  dotnet-agent-portal-gateway:
    build: 
      context: ../
      dockerfile: AgentPortalApiGateway/Dockerfile
    image: dotnet-agent-portal-gateway
    container_name: dotnet-agent-portal-gateway
    networks:
      - poc_default
    #    network_mode: host
    environment:
      eureka__client__serviceUrl: "http://eureka-server:8761/eureka"

  dotnet-auth-service:
    build: 
      context: ../
      dockerfile: AuthService/Dockerfile
    image: dotnet-auth-service
    container_name: dotnet-auth-service
    networks:
      - poc_default
    #    network_mode: host
    environment:
      eureka__client__serviceUrl: "http://eureka-server:8761/eureka"
  
  dotnet-chat-service:
    build: 
      context: ../
      dockerfile: ChatService/Dockerfile
    image: dotnet-chat-service
    container_name: dotnet-chat-service
    networks:
      - poc_default
    #    network_mode: host
    environment:
      eureka__client__serviceUrl: "http://eureka-server:8761/eureka"

  dotnet-payment-service:
    build: 
      context: ../
      dockerfile: PaymentService/Dockerfile
    image: dotnet-payment-service
    container_name: dotnet-payment-service
    networks:
      - poc_default
      #    network_mode: host
    environment:
      eureka__client__serviceUrl: "http://eureka-server:8761/eureka"

  dotnet-policy-search-service:
    build: 
      context: ../
      dockerfile: PolicySearchService/Dockerfile
    image: dotnet-policy-search-service
    container_name: dotnet-policy-search-service
    networks:
      - poc_default
    #    network_mode: host
    environment:
      eureka__client__serviceUrl: "http://eureka-server:8761/eureka"

  dotnet-policy-service:
    build: 
      context: ../
      dockerfile: PolicyService/Dockerfile
    image: dotnet-policy-service
    container_name: dotnet-policy-service
    networks:
      - poc_default
  #    network_mode: host
    environment:
      eureka__client__serviceUrl: "http://eureka-server:8761/eureka"
      ConnectionStrings__DefaultConnection: "User ID=lab_user;Password=lab_pass;Database=lab_netmicro_policy;Host=postgres;Port=5432"
      ConnectionStrings__RabbitMQ: "rabbit"


  dotnet-pricing-service:
    build: 
      context: ../
      dockerfile: PricingService/Dockerfile
    image: dotnet-pricing-service
    container_name: dotnet-pricing-service
    networks:
      - poc_default
    #    network_mode: host
    environment:
      eureka__client__serviceUrl: "http://eureka-server:8761/eureka"

  dotnet-product-service:
    build: 
      context: ../
      dockerfile: ProductService/Dockerfile
    image: dotnet-product-service
    container_name: dotnet-product-service
    networks:
      - poc_default
#    network_mode: host
    environment:
      eureka__client__serviceUrl: "http://eureka-server:8761/eureka"

  dotnet-web-vue:
    build: ../Web
    image: dotnet-web-vue
    container_name: dotnet-web-vue
    networks:
      - poc_default
    #    network_mode: host
    ports:
      - "5222:80"
    environment:
      eureka__client__serviceUrl: "http://eureka-server:8761/eureka"
      
networks:
  poc_default:
    name: poc_default