version: '3.5'

services:
  eureka:
    build: ../eureka-server
    image: eureka-server
    container_name: eureka-server
    networks:
      - poc_default
    ports:
      - 8761:8761

  postgres:
    build: ../postgres
    image: postgres
    container_name: postgres
    volumes:
      - /tmp/data/postgresql:/var/lib/postgresql/data
    networks:
      - poc_default
    ports:
      - 5432:5432

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - poc_default
    ports:
    - 9200:9200

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit
    networks:
      - poc_default
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      NAME: rabbitmq
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
    
networks:
  poc_default:
    name: poc_default